/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '17-7-25 下午6:16' with Gradle 3.0
 *
 * @author Administrator, @date 17-7-25 下午6:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
